<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update</title>
</head>
<body>
    <h1>Dados atualizados com sucesso!</h1>
    <h2><?= $username; ?></h2>
    <?= $email; ?></br>
    <?= $tel; ?></br>
    <?= $cep; ?></br>
    <?php //print_r($data); ?>
</body>
</html>